### ISSUE TITLE
Deploy.php doesn't support JSON Schema with "$ref": "#/definitions/"

### ISSUE THREAD

**Issue by SchwarzwaldFalke** [apioo/fusio-impl#1]
I'm generating my JSON Schema with PHP Annoations inside my Model class (See apioo/psx-schema#4).
If I use the `@Items(@Ref("FooClass"))` Annotation the JSON Schema Generator uses the "#/definitions" syntax to link the Definition of FooClass.
Example output:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "urn:schema.phpsx.org#",
  "definitions": {
    "Objectbfb8a532": {
      "type": "object",
      "properties": {
        "id": {},
      },
    }
  },
  "type": "object",
  "properties": {
    "urlReports": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Objectbfb8a532"
      }
    }
  },
}
```

Sadly I can't import this result with `php bin/fusio deploy` because only the `file:///xyz.json` scheme is supported in [Deploy.php:268](https://github.com/apioo/fusio-impl/blob/a57a982b5669705e94a80b2f6df51113982d7a70/src/Service/System/Deploy.php#L268).

The following change enables `#/definitions/` in Deploy.php:
```php
if ($uri->getScheme() == 'file') {
    $data->{$key} = $this->resolveRefs($basePath . '/' . $uri->getPath());
} else if (empty($uri->getScheme()) && 0 === stripos($data->{$key}->{'$ref'}, '#/definitions/')) {
    // Ref is inside the current file, do not resolve
    continue;
} else {
    throw new RuntimeException('Scheme ' . $uri->getScheme() . ' is not supported');
}
```
I did not test if this causes problems during API requests, backend actions, etc. !

**Comment by k42b3** [comment]
Hi, first thanks for this detailed report. The deploy command was introduced in the 0.7.1 release to have a simple tool to make changes to the API without using the backend UI. The idea was that the schema only includes file references, but if i think about it, it would make much more sense to allow also local references. In general I think we should ignore all URIs which are not absolute. So your fix is correct but I would simply use the `isAbsolute` method:

```php
if ($uri->isAbsolute()) {
	if ($uri->getScheme() == 'file') {
		$data->{$key} = $this->resolveRefs($basePath . '/' . $uri->getPath());
	} else {
		throw new RuntimeException('Scheme ' . $uri->getScheme() . ' is not supported');
	}
}
```

What do you think about this solution? If you like you could make a pull request to fix this issues otherwise I can also simply fix it.
