### ISSUE TITLE
System UserAdd command password restrictions

### ISSUE THREAD

**Issue by designermonkey** [apioo/fusio-impl#14]
I am using the docker example (modified) and the command `useradd` in this library is causing:

```
In Validator.php line 97:
Password must contain only printable ascii characters (0x21-0x7E)  
```

This is because I have spaces in my password. The printable character range of ascii characters includes spaces (`0x20`) so why are they not allowed or within the range described by the error? Range `0x20`-`0x7E` is printable.

https://www.systutorials.com/ascii-table-and-ascii-code/

**Comment by chriskapp** [comment]
Hi, so the initial reason was that whitespaces at the start/end could cause problems if someone trims or copies such passwords. But from a system view we could also easily include whitespaces since we store the passwords hashed s. https://github.com/apioo/fusio-impl/blob/master/src/Service/User/Validator.php#L86

**Comment by chriskapp** [comment]
I will close this issue, if there is a demand also from other users to allow including whitespaces we can easily relax this restriction.
